// This file is auto-generated by @hey-api/openapi-ts

export type applicationSettingsModel = {
    port: number;
    environmentVariables?: Array<environmentVariableModel>;
    command?: string;
};

export type buildSettings = {
    buildAllPullRequests: boolean;
    buildAllBranches: boolean;
    branchWildcard?: string;
    dockerFilePath?: string;
};

export type containerSettingsModel = {
    registry?: string;
    repository?: string;
};

export type environmentVariableModel = {
    key: string;
    value: string;
};

export type githubRepositoryModel = {
    name: string;
    owner: string;
};

export type gitSettingsModel = {
    repository: string;
    organization: string;
};

export type instanceGitSettingsModel = {
    branch?: string;
    commitHash?: string;
    pullRequestIdentifier?: string;
};

export type previewEnvironmentInstanceModel = {
    name: string;
    desiredPhase: string;
    currentPhase: string;
    ownerId: string;
    previewEnvironmentId: string;
    instanceGitSettings: instanceGitSettingsModel;
    publicFacingUrl?: string;
};

export type previewEnvironmentModel = {
    applicationSettings: applicationSettingsModel;
    containerSettings: containerSettingsModel;
    gitSettings: gitSettingsModel;
    buildSettings: buildSettings;
    name: string;
    id: string;
};

export type server_httpError = {
    message?: {
        [key: string]: unknown;
    };
};

export type PostEnvironmentData = {
    /**
     * Environment to create
     */
    body: previewEnvironmentModel;
    headers: {
        /**
         * Authentication token
         */
        authentication: string;
    };
};

export type PostEnvironmentResponse = (previewEnvironmentModel);

export type PostEnvironmentError = (server_httpError);

export type GetEnvironmentListData = {
    headers: {
        /**
         * Authentication token
         */
        authentication: string;
    };
};

export type GetEnvironmentListResponse = (Array<previewEnvironmentModel>);

export type GetEnvironmentListError = (server_httpError);

export type DeleteEnvironmentByIdData = {
    headers: {
        /**
         * Authentication token
         */
        authentication: string;
    };
    path: {
        /**
         * Id of the environment to delete
         */
        id: string;
    };
};

export type DeleteEnvironmentByIdResponse = (previewEnvironmentModel);

export type DeleteEnvironmentByIdError = (server_httpError);

export type GetEnvironmentInstanceByIdListData = {
    headers: {
        /**
         * Authentication token
         */
        authentication: string;
    };
    path: {
        /**
         * Id of the environment to list instances
         */
        id: string;
    };
};

export type GetEnvironmentInstanceByIdListResponse = (Array<previewEnvironmentInstanceModel>);

export type GetEnvironmentInstanceByIdListError = (server_httpError);

export type GetGithubRepositoriesData = {
    headers: {
        /**
         * Authentication token
         */
        authentication: string;
    };
};

export type GetGithubRepositoriesResponse = (Array<githubRepositoryModel>);

export type GetGithubRepositoriesError = (server_httpError);